[package]
name = "bm_os"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
crossbeam = "0.8.2"
crossbeam-channel = "0.5.6"
sfml = "0.19.0"
whisper-rs = "0.3.0"
